name: vanlanggo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/icons/
    - assets/riveAssets/

  fonts:
    - family: Colfax
      fonts:
        - asset: assets/fonts/Colfax-Black.otf
        - asset: assets/fonts/Colfax-Regular.otf
        - asset: assets/fonts/Colfax-Thin.otf
        - asset: assets/fonts/Colfax-Medium.otf
          weight: 500
        - asset: assets/fonts/Colfax-Bold.otf
          weight: 600
        - asset: assets/fonts/Colfax-Light.otf
          weight: 300
